version: '2.1'
services:
  node:
    image: node-hello-world:latest
    ports:
      - "172.17.0.1:49153:8080"
    security_opt:
      - no-new-privileges
    pids_limit: 100
    mem_limit: 256m
    cpu_shares: 512
    restart: on-failure:5
    read_only: true
